DB_URL: jdbc:postgresql://postgres:5432/walletdb?currentSchema=public
DB_USERNAME: "postgres"
DB_PASSWORD: "postgres"
DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
DRIVER_CLASSNAME: org.postgresql.Driver

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false #auto commit
      maximum-pool-size: 10 #maximum pool size
      leak-detection-threshold: 30000
      max-lifetime: 60000
      connection-timeout: 20000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.example.demo: DEBUG